---
# This play will ONLY execute if 'process_audit_remove_rule' is explicitly set to true.
- name: "03.1 | REMOVE: Permanent audit rule file if requested (Cleanup)"
  ansible.builtin.file:
    path: "{{ audit_rule_name }}"
    state: absent
  when: process_audit_remove_rule | bool
  notify: reload auditd
  tags:
    - audit_rule_remove
