# vars file for instana-agent-windows
---
# Name of the Instana offline installer executable
instana_installer_file: "instana-agent-windows-64bit-j9-offline.exe"

# Temporary directory on the Windows target for the installer file
instana_staging_dir: "C:\\InstanaTemp"

# Instana Backend Configuration Details
instana_agent_endpoint: "agent-acceptor.instanapoc.rbi1.rbi.org.in"
instana_agent_port: 443
instana_agent_key: "qvRFSyR2euGlcYdfjsbnMv"
instana_download_key: "8Q5NYGutQveLtKVLyIPhLQ"

# Windows Service Name (Default name created by the Instana installer)
instana_agent_service_name: "instana-agent-service"
instana_hosts_file: "C:\\Windows\\System32\\drivers\\etc\\hosts"

# List of host entries to add to C:\Windows\System32\drivers\etc\hosts
instana_hosts_entries:
  - ip: "10.29.7.39"
    name: "instanapilot.rbi1.rbi.org.in"
  - ip: "10.29.7.39"
    name: "ingress.instanapilot.rbi1.rbi.org.in"
  - ip: "10.29.7.39"
    name: "otlp-http.instanapilot.rbi1.rbi.org.in"
  - ip: "10.29.7.39"
    name: "otlp-grpc.instanapilot.rbi1.rbi.org.in"
  - ip: "10.29.7.39"
    name: "agent-acceptor.instanapilot.rbi1.rbi.org.in"
  - ip: "10.29.7.39"
    name: "pilot-rbi.instanapilot.rbi1.rbi.org.in"
