#SPDX-License-Identifier: MIT-0
---
# handlers file for MONITORING_process_audit
# handlers/main.yml
- name: "Load audit rules without restarting auditd"
  ansible.builtin.command: augenrules --load
  become: true
  changed_when: false