#SPDX-License-Identifier: MIT-0
---
# handlers file for MONITORING_process_audit
# handlers/main.yml
- name: reload auditd # <-- THIS MUST MATCH THE NOTIFY STRING EXACTLY
  ansible.builtin.service:
    name: auditd
    state: restarted